force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Sell_Rate__c.field-meta.xml
<CustomField>
    <fullName>Sell_Rate__c</fullName>
    <formula>TEXT(Currency__c) &amp; &quot;/&quot; &amp; TEXT(Client_Bill_Rate__c) &amp; &quot;/&quot; &amp; TEXT(Pay_Period__c) &amp; &quot;/&quot; &amp; TEXT(Employment_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sell Rate</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Vendor_Account__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/Job_Submission__c.object-meta.xml
<CustomObject>
    <label>Job Submission</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Submission__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <inlineHelpText>Enter Consultant Email Address</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Enter Consultant First Name</inlineHelpText>
    <label>First Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Choose the Appropriate Job to apply</inlineHelpText>
    <label>Job ID</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Submissions</relationshipLabel>
    <relationshipName>Job_Submissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Job_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Job_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Job Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <inlineHelpText>Enter Consultant Phone Number</inlineHelpText>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Sales_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Sales_Team_Member__c</fullName>
    <inlineHelpText>Enter the Name of Sales Team Member</inlineHelpText>
    <label>Sales Team Member</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Talent_Bench_ID__c.field-meta.xml
<CustomField>
    <fullName>Talent_Bench_ID__c</fullName>
    <label>Talent Bench ID</label>
    <referenceTo>Talent_Bench__c</referenceTo>
    <relationshipLabel>Job Submissions</relationshipLabel>
    <relationshipName>Job_Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Work_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Work_Authorization__c</fullName>
    <label>Work Authorization</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>GC</fullName>
            </value>
            <value>
                <fullName>GC-EAD</fullName>
            </value>
            <value>
                <fullName>H1-B</fullName>
            </value>
            <value>
                <fullName>L1-A</fullName>
            </value>
            <value>
                <fullName>L1-B</fullName>
            </value>
            <value>
                <fullName>L2-EAD</fullName>
            </value>
            <value>
                <fullName>OPT-EAD</fullName>
            </value>
            <value>
                <fullName>TV Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Talent_Bench__c/Talent_Bench__c.object-meta.xml
<CustomObject>
    <label>Talent Bench</label>
    <nameField>
        <displayFormat>TB_ID{0000}</displayFormat>
        <label>Talent Bench ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Talent Benches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talent_Bench__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Enter Consultant Email Address</inlineHelpText>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Talent_Bench__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Enter Consultant First Name</inlineHelpText>
    <label>First Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Talent_Bench__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <inlineHelpText>Enter Valid 10 digit Phone Number</inlineHelpText>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/VendorSubmissions.cls
public with sharing class VendorSubmissions {
    @AuraEnabled(cacheable=true)
    public static List<Job_Submission__c> getVendorSubmissions(String filter, String selectedValue, Date customStartDate, Date customEndDate) {
        Date today = Date.today();
        Date startDate;
        Date endDate;
        if (filter == 'daily') {
            startDate = today;
            endDate = today;
        } else if (filter == 'weekly') {
            startDate = today.toStartOfWeek();
            endDate = startDate.addDays(6);
        } else if (filter == 'monthly') {
            Integer month = Integer.valueOf(selectedValue);
            Integer year = today.year();
            startDate = Date.newInstance(year, month, 1);
            endDate = Date.newInstance(year, month, daysInMonth(year, month));
        } else if (filter == 'yearly') {
            Integer year = Integer.valueOf(selectedValue);
            startDate = Date.newInstance(year, 1, 1);
            endDate = Date.newInstance(year, 12, 31);
        } else if (filter == 'custom') {
            if (customStartDate != null && customEndDate != null) {
                startDate = customStartDate;
                endDate = customEndDate;
            } else {
                throw new IllegalArgumentException('Custom dates must be provided for the custom filter');
            }
        } else {
            startDate = today;
            endDate = today;
        }

        system.debug('Start Date: ' + startDate + ', End Date: ' + endDate);

        String query = 'SELECT Job_ID__r.Name, Job_Title__c, Job_ID__r.Vendor_Account__r.Name, Job_ID__r.Sell_Rate__c, Talent_Bench_ID__r.Name, First_Name__c, Email_Address__c, Phone_Number__c, LinkedIn_Profile__c, Work_Authorization__c, Sales_Team_Member__c, CreatedDate FROM Job_Submission__c WHERE Job_Submitted__c = true AND CreatedDate >= :startDate AND CreatedDate <= :endDate';
        List<Job_Submission__c> results = Database.query(query);
        System.debug(results);
        return results;
    }

    public static Integer daysInMonth(Integer year, Integer month) {
        if (month == 1 || month == 3 || month == 5 || month == 7 || month == 8 || month == 10 || month == 12) {
            return 31;
        } else if (month == 4 || month == 6 || month == 9 || month == 11) {
            return 30;
        } else if (month == 2) {
            return Date.isLeapYear(year) ? 29 : 28;
        } else {
            throw new IllegalArgumentException('Invalid month: ' + month);
        }
    }
    public static void Test(){
        System.debug('Test Method');
        System.debug('Method');
    }
}