force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Submission__c/Job_Submission__c.object-meta.xml
<CustomObject>
    <label>Job Submission</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Submission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Submission__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <inlineHelpText>Enter Consultant Email Address</inlineHelpText>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Enter Consultant First Name</inlineHelpText>
    <label>First Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Choose the Appropriate Job to apply</inlineHelpText>
    <label>Job ID</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Submissions</relationshipLabel>
    <relationshipName>Job_Submissions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Enter Consultant Last Name</inlineHelpText>
    <label>Last Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <inlineHelpText>Enter Consultant Phone Number</inlineHelpText>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Job_Submission__c/fields/Talent_Bench_ID__c.field-meta.xml
<CustomField>
    <fullName>Talent_Bench_ID__c</fullName>
    <label>Talent Bench ID</label>
    <referenceTo>Talent_Bench__c</referenceTo>
    <relationshipLabel>Job Submissions</relationshipLabel>
    <relationshipName>Job_Submissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Talent_Bench__c/Talent_Bench__c.object-meta.xml
<CustomObject>
    <label>Talent Bench</label>
    <nameField>
        <displayFormat>TB_ID{0000}</displayFormat>
        <label>Talent Bench ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Talent Benches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talent_Bench__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Enter Consultant Email Address</inlineHelpText>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Talent_Bench__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Enter Consultant First Name</inlineHelpText>
    <label>First Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Talent_Bench__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Enter Consultant Last Name</inlineHelpText>
    <label>Last Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Talent_Bench__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <inlineHelpText>Enter Valid 10 digit Phone Number</inlineHelpText>
    <label>Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/Talent_Bench_Data.cls
public with sharing class Talent_Bench_Data {
    @AuraEnabled(cacheable=true)
    public static List<Talent_Bench__c> getTalentBenchRecords(string recordId) {
        // return [SELECT Name, First_Name__c, Last_Name__c, Email_Address__c, Phone_Number__c
        //         FROM Talent_Bench__c WHERE ID=:recordId];
        List<Talent_Bench__c> talentBenchList =  [SELECT Id, Name, First_Name__c, Last_Name__c, Email_Address__c, Phone_Number__c FROM Talent_Bench__c WHERE Id=:recordId];
        System.debug('Talent Bench Data::' + talentBenchList);
        return talentBenchList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Job_Submission__c> getJobDetails(String talentBenchId) {
        List<Job_Submission__c> jobSubmissionList = [SELECT Talent_Bench_ID__c, Talent_Bench_ID__r.Name, First_Name__c, Last_Name__c, Job_Id__c, Job_ID__r.Name, Job_Title__c, Email_Address__c, Phone_Number__c
                FROM Job_Submission__c
                WHERE Talent_Bench_ID__c = :talentBenchId];
        
        System.debug('Job Submission Data::' + jobSubmissionList);
        return jobSubmissionList;
    }

}